baseURL = 'localhost'
languageCode = 'en-us'
title = 'Wxf`s Fantasy World'
theme = 'smigle'



[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 5

[params]
abbrDateFmt = "Jan 2"
author = "Blog Author"
brandIconFile = "images/brandIcon.svg"
dateFmt = "2006-01-02"
subtitle = "share something useful"



[[params.social]]
name = "GitHub"
url = "https://github.com/apeishuai"
[[params.social]]
name = "Bilibili"
url = "https://github.com/apeishuai"
[[params.social]]
name = "Weibo"
url = "https://github.com/apeishuai"



